apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apm

resources:
  - namespace.yaml
  - clickhouse/configmap.yaml
  - clickhouse/secret.yaml
  - clickhouse/service.yaml
  - clickhouse/statefulset.yaml
  - ollama/pvc.yaml
  - ollama/deployment.yaml
  - ollama/service.yaml
  - qdrant/statefulset.yaml
  - qdrant/service.yaml
  - collector/pvc.yaml
  - collector/configmap.yaml
  - collector/secret.yaml
  - collector/deployment.yaml
  - collector/service.yaml
  - collector/hpa.yaml
  - collector/pdb.yaml
